spring:
  application:
    name: "MOVIESCATALOGSERVICE"

resilience4j:
  retry:
    instances:
      myRetry:
        MaxRetryAttempts: 3
        wait-duration: 5s


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost